export const LOAD_COLLECTORS = "LOAD_COLLECTORS"
export const CREATE_COLLECTOR = "CREATE_COLLECTOR"
export const LOAD_COLLECTOR_DETAIL = "LOAD_COLLECTOR_DETAIL"
export const DELETE_COLLECTOR = "DELETE_COLLECTOR"